### ISSUE TITLE
Synthesis data

### ISSUE THREAD

**Issue by wyhlovecpp** [mobaidoctor/med-ddpm#19]
Hi, thank you very much for this work. But I have a question about the data used to train 3D-Unet.

You mentioned in the paper that you used 1,000 real data and 1,000 synthetic data. But you didn't say where the 1000 real data came from and where the mask labels came from for the synthetic data, whether they are the same mask or not

**Comment by wyhlovecpp** [comment]
Also, when you did this experiment, you had a combination of 1000 real images and 2000 synthetic images. I want to know if you used a different mask for the 2000 images or if you synthesized from the masks of the 1000 real images twice (DDPM is SDE, repeated synthesis will make a difference). Looking forward to your reply

**Comment by mobaidoctor** [comment]
Hi @wyhlovecpp, Thank you for your questions. We apologize for the delayed response due to some urgent research tasks. Regarding the 1,000 real images, they were randomly selected from our dataset, which consists of 1,500 images. Subsequently, we generated 1,000 synthetic images using the exact masks from these selected 1,000 real images. As for the synthetic 2,000 images, we created new masks based on those selected 1,000 masks by scaling the tumor mask from its center and shifting the tumor mask within the head mask in the x, y, and z directions. We have made our mask generator script available in our repository, which can be found at https://github.com/mobaidoctor/med-ddpm/blob/main/mask_generator.ipynb. If you need further clarification or have more questions, please do not hesitate to contact us. Thank you.
