### ISSUE TITLE
ERROR: Can't pickle <function <lambda> 

### ISSUE THREAD

**Issue by kitofito** [mobaidoctor/med-ddpm#5]
Hello, thank you very much for your previous response to my issue. I've been encountering the following error for many weeks, and I still don't know how to resolve it. I would greatly appreciate it if you could help me fix this error, please.

Thank you.
![Med-DDPM_error](https://github.com/mobaidoctor/med-ddpm/assets/142527427/e611a979-a21c-4bab-aeb2-a76335b2f6c9)

**Comment by kitofito** [comment]
I ran the project in Google Colab, and it worked for me!

**Comment by mobaidoctor** [comment]
Hi, @kitofito, thank you for reaching out. Which version of Python are you using? The "pickle.PicklingError: Can't pickle <lambda>" error arises because Python's pickle module cannot serialize lambda functions. Here are some simple steps to resolve the issue:
 - Convert lambdas to standard functions.
 - Utilize the dill library.
If you continue to experience problems after trying these solutions, please let us know. Thank you.
