### ISSUE TITLE
Preprocessing for brast21 data

### ISSUE THREAD

**Issue by xiyuez2** [mobaidoctor/med-ddpm#8]
Thank you for your great work! 

I am trying to reproduce your results on brast21. I can reproduce the inference results using the example files you provide. 

However, I noticed that the files you provided have gone through some preprocessing, such as normalizing. I wonder whether you can share the way you preprocess the 3D images, which is crucial for reproducing the training of the model.

Thanks!

**Comment by mobaidoctor** [comment]
Thank you for your interest in our work and for your inquiry. The preprocessing steps for the BraTS dataset are detailed in our manuscript (https://arxiv.org/pdf/2305.18453.pdf) in the section titled 'F. 3D Multimodal MRI Synthesis Experiment' on pages 9 and 10. We utilized the CropOrPad function from the TorchIO library to crop the original images to a size of 192x192x144. Additionally, since the original BraTS dataset's mask images do not include a label for brain shape, we added this label by simply thresholding the T1 images. If you have any further questions, please feel free to let us know.

**Comment by TUAT-Novice** [comment]
> Thank you for your great work!
> 
> I am trying to reproduce your results on brast21. I can reproduce the inference results using the example files you provide.
> 
> However, I noticed that the files you provided have gone through some preprocessing, such as normalizing. I wonder whether you can share the way you preprocess the 3D images, which is crucial for reproducing the training of the model.
> 
> Thanks!

@xiyuez2 Hi, xiyuez2. I also try to reproduce their results on brats21 dataset. However, I can only obtain awful MRI. I would like to know if you have made any changes to their code, or if you have used their "model_brans.pt" checkpoint to directly process and generate data using "preprocess_brans.data.py" and "sample_brans.py" scripts, respectively?
